name: Deploy Laravel to Render

on:
  push:
    branches:
      - main  # deploy when main branch is updated

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to Render CLI
        run: |
          curl -fsSL https://cdn.render.com/cli/latest/install.sh | bash
        shell: bash

      - name: Deploy to Render
        run: |
          render login --api-key ${{ secrets.RENDER_API_KEY }}
          # Replace <service-id> with your Render Web Service ID
          render deploy <service-id>
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
