name: Deploy Laravel to Vercel

on:
  push:
    branches:
      - main   # or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout
        uses: actions/checkout@v3

      # 2. Set up PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, intl
          tools: composer:v2

      # 3. Install PHP dependencies
      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader

      # 4. Install Node (if Laravel Mix/Vite used)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 5. Install JS dependencies & build assets (optional)
      - name: Install NPM dependencies
        run: npm install

      - name: Build assets
        run: npm run build || echo "No build script found"

      # 6. Deploy to Vercel
      - name: Deploy to Vercel
        run: npx vercel --prod --yes
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
