name: Deploy Laravel to Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v3

      # Set up PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, bcmath, intl
          coverage: none

      # Install Composer dependencies
      - name: Install PHP dependencies
        run: composer install --no-dev --optimize-autoloader

      # Generate Vercel build output
      - name: Build with Vercel
        run: npx vercel build --prod --yes --token=${{ secrets.VERCEL_TOKEN }}

      # Deploy prebuilt output to Vercel
      - name: Deploy to Vercel
        run: npx vercel deploy --prebuilt --prod --yes --token=${{ secrets.VERCEL_TOKEN }}
