name: Deploy Laravel to Vercel

on:
  push:
    branches:
      - main   # Change if your default branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, intl
          tools: composer:v2

      # 3. Install PHP dependencies
      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader

      # 4. Set up Node.js (if you use Laravel Mix or Vite)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 5. Install JS dependencies & build assets
      - name: Install NPM dependencies
        run: npm install

      - name: Build frontend assets
        run: npm run build || echo "No build script found"

      # 6. Cache Laravel configuration
      - name: Optimize Laravel
        run: |
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache || true

      # 7. Deploy to Vercel
      - name: Deploy to Vercel
        run: npx vercel --prod --yes --token=${{ secrets.VERCEL_TOKEN }}
